### PR TITLE
improved golang example

### PR DESCRIPTION
**Pull request by garciaolais**

### CODE REVIEW

**Comment by kyle-github** [comment]
Thanks!

**Comment by kyle-github** [comment]
I will be splitting off the wrappers into separate repos in the near future.   I also would like to change the core library license to the MPL 2.0.   Would you have any objections to that?  The Go wrapper can still be maintained with LGPL if you prefer, but I am hoping to have all the wrappers and core use the same license to keep things simple.

Thanks for considering this.

Best,
Kyle

**Comment by garciaolais** [comment]
I don't have any problem with that 🚀 👍

**Comment by kyle-github** [comment]
Thanks!

**Comment by TheFern2** [comment]
Does this wrapper work on win10?

**Pull request merged**
