### PR TITLE
Add C++ wrapper example for v2.0+

### PR DESCRIPTION
**Pull request by xinthose**
Hello.  I am updating / moving my code that is up to date with your library.  I have tested my `plctag` class very much in industry, but not this example code per say.  The Boost libraries are required.

### CODE REVIEW

**Comment by kyle-github** [comment]
Looks good.   Thanks for doing this!

**Comment by kyle-github** [comment]
Note that if you want to allow C++ to read the tag list, it will take some replumbing.   When you want to read the list of tags, you do not pass an element size or count.

**Comment by xinthose** [comment]
OK.  Thank you and you're welcome Kyle!

**Comment by kyle-github** [comment]
Hey @xinthose, 

I want to relicense the library to a dual MPL 2.0 and LGPL license.   The wrappers can stay with LGPL or move as well.  That said, it would be nice if everything could be relicensed to the same dual license for simplicity.

Please let me know your thoughts on this.

Best,
Kyle

**Comment by xinthose** [comment]
Hello Kyle.  Yes, that is fine with me.  Thank you for your professionalism.  I also plan on updating this contribution code soon.

**Pull request merged**
