### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by Donnie-github**
I added a solution with the three projects. The library, the tag_rw and the string samples. The sample projects refer to the source in the Sample folder. I updated some operators in the samples cause VS didn't want to build them. Please review if the new operators are ok under linux. It looks like tag_rw works ok. It tries to connect to a PLC. I haven't tested it yet with a real PLC.

### CODE REVIEW

**Comment by dlbrown06** [comment]
+1

Is anyone looking into getting this pulled into the project. We are trying to get this to work on windows right now. Haven't had much success yet and would love to give this a try.

We have a number of different AB PLCs we can test this against.

**Comment by thatcadguy** [comment]
If you want to try it, download from the branch being proposed to merge: https://github.com/Donnie-github/libplctag/tree/Windows-support

**Comment by thatcadguy** [comment]
You can also try TuxPLC, which is now LGPL licensed.

**Comment by dlbrown06** [comment]
Thanks for the quick response!

**Comment by kyle-github** [comment]
Hi Douglas,

Sorry for the delay.  I seem to not see this issue (#17) in GitHub, but the
one with the same name (#16) doesn't have these comments...  Weird.

I'll try to reopen the Windows support ticket.

I got tag_rw to work with Visual Studio, just not the same way that Donnie
did.

Is it the .sln for the IDE that you want?

@Jacob, do you mean TuxEIP?  Or is there another project?  I'd love to see
more!

Best,
Kyle

**Comment by thatcadguy** [comment]
https://github.com/leicht/TuxPLC
I've used it with a MicroLogix and a CompactLogix, works okay (reads/writes
ints, floats) but the code needed some fixing up, still kind of does. I
thought TuxPLC was what you were referring to in your readme writeup on
your main GitHub page.

**Comment by kyle-github** [comment]
I am going to close this as soon as I finish the CMake-based build system.  I am working on that now.  This will allow me to support VC++ in a much more "native" way and should be a lot friendlier for Windows users.    CMake is a very different animal than I am used to, so this is taking a while.  However, it promises to provide much better support for different platforms.

I have CMake working for the Linux build already, but I need to do a lot more testing.

**Comment by kyle-github** [comment]
I am going to close this as soon as 1.5 is released.  1.5 is based on CMake and seems to work fine in Microsoft Visual Studio Community Edition 2016.  It builds a project file with all the right dependencies and correctly sets up the library and builds the Windows-compatible examples.

**Comment by kyle-github** [comment]
I am closing this.  The newly released version 1.5 includes CMake support and through that, supports MSVC directly.  The NMake files have been removed.

**Pull request closed without merging**
